export type TModelNameEs =
  | ''
  | 'Residente'
  | 'Rol'
  | 'Centro'
  | 'Usuario'
  | 'Residente Responsable'
  | 'LAC'
  | 'Apariencia'
  | 'Contacto'
  | 'Grupo'
  | 'Incidencia'
  | 'AVD'
  | 'Médico'
  | 'Usuario Residente'
  | 'Medicamento'
  | 'EmployeeFile'
  | 'Asignación de Permisos'
  | 'Modulo'
  ;
