import { sId } from './api.interfaces';

export type TPath =
  | 'assign-residents'
  | 'avd'
  | 'avds'
  | 'billings'
  | 'centers'
  | 'centers'
  | 'clinical-course'
  | 'daily-living-activities-categories'
  | 'daily-living-activities'
  | 'dashboard'
  | 'employees'
  | 'files'
  | 'guideline-diapers'
  | 'historical-medications'
  | 'history-medication'
  | 'incidents'
  | 'kitchens'
  | 'medications'
  | 'occupations'
  | 'internal-chat'
  | 'patient'
  | 'permission'
  | 'profile-employee'
  | 'profile-medico'
  | 'profile'
  | 'resident'
  | 'residents'
  | 'roles'
  | 'user-residents'
  | 'users'
  | 'template-managers'
  | 'shopping'
  | 'answer-questionary'
  | 'history-questionary'
  | 'response-questionary'
  | 'dishes'
  | 'menu-kitchens'
  | 'forecasts'
  | 'ingredients'
  | 'resident-avd-detail'
  | 'schedules'
  | 'calendars'
  | 'laundries'
  | 'clothes'
  | 'groups'
  | 'medical-drugs'
  | 'pharmacies'
  | 'guideline-medications'
  | 'cleaning-maintenance'
  | 'reminder-calendars'
  | 'drinking-records'
  | 'drinking-record-expire'
  | 'guideline-feeding'
  | 'objects'
  | 'setting'
  | 'personal-objects'
  | 'billings'
  | 'contracts'
  | 'crm'
  | 'inspections'
  | 'configuration'
  | 'providers'
  | 'clients'
  | 'services'
  | 'taxes'
  | 'payers'
  | 'payment-terms'
  | 'contracts-docs'
  | 'templates'
  | 'settings'
  | 'drinking-record-expire'
  | 'activities'
  | 'phases'
  | 'reason-lost'
  | 'tags'
  | 'center-clinical-course'
  | 'purchases'
  | 'history'
  | 'register'
  | 'sale-rectifies'
  | 'purchase-rectifies'
  | 'allergies'
  | 'registers'
  | 'check-in-out'
  | 'tutor'
  | 'sales'
  | 'resident-tests'
  | 'contract-types'
  | 'payment-term'
  | 'employee-tests'
  | 'configurations'
  | 'activities';

export type TNavEdit = `edit/:${string}`;

export type TActionPath = 'list' | 'create' | 'edit';

/* export type TPathComplement = `answer-questionary/:${string}`; */

type TTypeId = 'id' | 'residentId' | 'employeeId';

export type INav =
  | ''
  | ':id'
  | `:${string}`
  | TActionPath
  | `${TActionPath}/:${TTypeId}`
  | `${TActionPath}/:${TTypeId}/answer-questionary/:id`
  | `${TActionPath}/:${TTypeId}/history-questionary/:id`
  | /* TPathComplement | */ TNavEdit
  | `${TPath}`
  | `${TPath}/:${string}`
  | `${TPath}/${TActionPath}`
  | `${TPath}/${TActionPath}/:${TTypeId}`
  | '**';

export type IRoute = `/${TPath}/${TActionPath}`;

export enum PathToRedirect {
  '/residents/$uuid' = '/residents/profile/$uuid',
}

export type TPathUuid = '$uuid';

export type TRoutePattern =
  | `/activities/create`
  | `/activities/list`
  | `/allergies`
  | `/allergies/list`
  | `/allergies/create`
  | `/allergies/${sId}`
  | '/crm'
  | '/crm/list'
  | '/crm/create'
  | `/crm/${sId}`
  | '/crm/phases'
  | '/crm/phases/create'
  | `/crm/phases/${sId}`
  | '/crm/reason-lost'
  | '/crm/reason-lost/create'
  | `/crm/reason-lost/${sId}`
  | '/crm/tags'
  | '/crm/tags/create'
  | `/crm/tags/${sId}`
  | '/crm/activities'
  | '/crm/activities/list'
  | '/crm/activities/create'
  | `/crm/activities/${sId}`
  | '/groups/list'
  | `/billings`
  | `/billings/clients`
  | `/billings/clients/create`
  | `/billings/clients/list`
  | `/billings/clients/${sId}`
  | `/billings/configuration`
  | `/billings/providers/${sId}`
  | `/billings/providers/create`
  | `/billings/providers/list`
  | `/billings/providers`
  | `/billings/services`
  | `/billings/taxes`
  | `/billings/payment-terms/create`
  | `/billings/payment-terms/${sId}`
  | `/billings/purchases`
  | `/billings/purchases/create`
  | `/billings/purchases/list`
  | `/billings/purchases/${sId}`
  | `/billings`
  | `/billings/list`
  | `/billings/edit/${sId}`
  | `/billings/sales/${sId}/payment-term`
  | `/billings/sale-rectifies/list`
  | `/billings/purchase-rectifies/list`
  | `/centers/create`
  | `/centers/list`
  | `/cleaning-maintenance/internal-chat`
  | `/cleaning-maintenance/shopping`
  | `/commercial-management/create`
  | `/commercial-management`
  | `/contracts-docs/contracts`
  | `/contracts-docs/settings`
  | `/contracts-docs/templates`
  | `/daily-living-activities-categories`
  | `/daily-living-activities/create`
  | `/daily-living-activities`
  | `/dashboard-reporting/create`
  | `/dashboard-reporting/list`
  | `/employees`
  | `/employees/create`
  | `/employees/edit/${sId}`
  | `/employees/schedules/list/${sId}`
  | `/employees/schedules/create/${sId}`
  | `/employees/schedules/${sId}`
  | `/employees/profile-employee/${sId}`
  | `/employees/registers`
  | `/employees/check-in-out`
  | `/groups/create`
  | `/groups/list`
  | `/groups`
  | `/inspections`
  | `/inspections/create`
  | `/inspections/list`
  | `/kitchens/calendars`
  | `/kitchens/dishes`
  | `/kitchens/forecasts`
  | `/kitchens/ingredients`
  | `/kitchens/menu-kitchens`
  | `/laundries/clothes/${sId}`
  | `/laundries/clothes/create`
  | `/laundries/clothes/list/${sId}`
  | `/laundries/clothes`
  | `/laundries/list`
  | `/laundries/shopping`
  | `/medical-drugs/list`
  | `/occupations`
  | `/residents/${sId}/avds`
  | `/residents/${sId}/avds/${sId}`
  | `/residents/${sId}/contracts`
  | `/residents/${sId}/contracts/create`
  | `/residents/${sId}/contracts/${sId}`
  | `/contracts-docs/contracts/edit/${sId}`
  | `/contracts-docs/contract-types`
  | `/contracts-docs/contract-types/list`
  | `/contracts-docs/contract-types/create`
  | `/contracts-docs/contract-types/${sId}`
  | `/personal-objects`
  | `/personal-objects/create`
  | `/personal-objects/${sId}`
  | `/personal-objects/create`
  | `/personal-objects`
  | `/pharmacies/drinking-records`
  | `/pharmacies/drinking-record-expire`
  | `/pharmacies/guideline-medications`
  | `/pharmacies/setting`
  | `/reminder-calendars/list`
  | `/residents/${sId}/avds/${sId}`
  | `/residents/${sId}/avds`
  | `/residents/${sId}/clothes/${sId}`
  | `/residents/${sId}/clothes/create`
  | `/residents/${sId}/clothes`
  | `/residents/${sId}/contracts/create`
  | `/residents/${sId}/contracts`
  | `/residents/${sId}/medications/${sId}`
  | `/residents/${sId}/tutor`
  | `/residents/${sId}/allergies`
  | `/residents/${sId}/medications`
  | `/residents/${sId}/clinical-course`
  | `/residents/${sId}/guideline-diapers`
  | `/residents/${sId}/guideline-feeding`
  | `/residents/${sId}/objects`
  | `/residents/patient/create`
  | `/residents/patient/list`
  | `/residents/patient/${sId}`
  | `/roles/create`
  | `/roles/list`
  | `/template-managers/create`
  | `/template-managers/list`
  | `/user-residents`
  | `/users/create`
  | `/users/list`
  | `/template-managers/history-questionary/${sId}`
  | '/activities/create'
  | '/activities/list'
  | '/billings/clients/list'
  | '/billings/list'
  | '/billings/providers/list'
  | '/billings/services'
  | '/billings/taxes'
  | '/centers/create'
  | '/center-clinical-course'
  | '/centers/list'
  | '/cleaning-maintenance/internal-chat'
  | '/cleaning-maintenance/shopping'
  | '/crm'
  | '/contracts-docs/settings'
  | '/contracts-docs/templates'
  | '/daily-living-activities-categories'
  | '/daily-living-activities'
  | '/daily-living-activities/list'
  | '/daily-living-activities/create'
  | `/daily-living-activities/edit/${sId}`
  | '/daily-living-activities/history'
  | '/daily-living-activities/register'
  | '/employees'
  | '/employees/create'
  | '/employees/list'
  | '/groups'
  | '/groups/create'
  | `/inspections`
  | `/inspections/create`
  | `/inspections/list`
  | `/inspections/${sId}`
  | '/kitchens/calendars'
  | '/kitchens/dishes'
  | '/kitchens/forecasts'
  | '/kitchens/ingredients'
  | '/kitchens/menu-kitchens'
  | '/laundries/list'
  | '/laundries/shopping'
  | '/medical-drugs/list'
  | '/occupations'
  | '/reminder-calendars/list'
  | '/residents/patient'
  | '/residents/patient/create'
  | `/residents/patient/${sId}`
  | '/residents/patient/list'
  | '/roles/create'
  | '/roles/list'
  | '/template-managers/create'
  | '/template-managers/list'
  | '/configurations'
  | '/resident-tests/create'
  | '/resident-tests/list'
  | `/resident-tests/create`
  | `/resident-tests/history-questionary/${sId}`
  | `/resident-tests/response-questionary/${sId}`
  | `/resident-tests/list`
  | `/resident-tests/list/${sId}/answer-questionary/${sId}`
  | `/resident-tests/list/${sId}/history-questionary/${sId}`
  | `/resident-tests/list/${sId}`
  | `/resident-tests/edit/${sId}`
  // | `/resident-tests/${sId}`
  /*
  TODO: Eliminar si ya no es necesario(modulo: template test-empleoyee)
  | '/employee-tests/create'
  | '/employee-tests/list'
  | `/employee-tests/create`
  | `/employee-tests/history-questionary/${sId}`
  | `/employee-tests/response-questionary/${sId}`
  | `/employee-tests/list`
  | `/employee-tests/list/${sId}/answer-questionary/${sId}`
  | `/employee-tests/list/${sId}/history-questionary/${sId}`
  | `/employee-tests/list/${sId}`
  | `/employee-tests/edit/${sId}` */
  // | `/employee-tests/${sId}`
  | '/user-residents'
  | '/users/create'
  | '/users/list';
